export const CHANGE_TITLE_FILTER = "CHANGE_TITLE_FILTER";
export const SORT_BOOKS = "SORT_BOOKS";
export const CHANGE_DATE_FILTER = "CHANGE_DATE_FILTER";
export const CHANGE_PUBLISHERS_FILTER = "CHANGE_PUBLISHERS_FILTER";
export const CHANGE_AUTHORS_FILTER = "CHANGE_AUTHORS_FILTER";
export const ADD_FAVORITE_BOOK = "ADD_FAVORITE_BOOK";
export const REMOVE_FAVORITE_BOOK = "REMOVE_FAVORITE_BOOK";

export const DEFAULT_ORDER = "_DEFAULT_ORDER";
export const DATE_ASCENDING_ORDER = "_DATE_ASCENDING_ORDER";
export const DATE_DESCENDING_ORDER = "_DATE_DESCENDING_ORDER";
export const RATING_ASCENDING_ORDER = "_RATING_ASCENDING_ORDER";
export const RATING_DESCENDING_ORDER = "_RATING_DESCENDING_ORDER";
export const ALPHABET_ASCENDING_ORDER = "_ALPHABET_ASCENDING_ORDER";
export const ALPHABET_DESCENDING_ORDER = "_ALPHABET_DESCENDING_ORDER";
